### ISSUE TITLE
Safari v12.1.2 - SyntaxError: The string did not match the expected pattern

### ISSUE THREAD

**Issue by frugan-it** [KreutzerCode/configurable-date-input-polyfill#10]
I'm testing a simple date input on Safari v12.1.2 via BrowserStack:

```html
<input name="foo" type="date">
```

and I get the following error in the console:

```
SyntaxError: The string did not match the expected pattern
```
![Schermata da 2023-10-22 18-17-32](https://github.com/KreutzerCode/configurable-date-input-polyfill/assets/7957714/f649d38c-89ac-4f2b-a0fe-7311511a9f96)

and the calendar does not appear in the input.

The error appears both when compiling with Webpack:

```ts
import 'configurable-date-input-polyfill';
```
and directly calling the polyfill via script:

```html
<script src="https://raw.githack.com/KreutzerCode/configurable-date-input-polyfill/master/dist/configurable-date-input-polyfill.dist.js"></script>
```

The polyfill works with Safari v13.1 and above.

**Comment by KreutzerCode** [comment]
Hi @frugan-it,

Thank you for reporting the problem. 
I will replicate the described test setup as soon as possible and report back.

**Comment by KreutzerCode** [comment]
Hi @frugan-it,

I managed to reproduce the error in Safari v12.1 as you described. Nice catch!

I provided a fix that will be included in the next version.

Thanks again for reporting the problem.

**Comment by frugan-it** [comment]
Super fast! Great thanks! :stuck_out_tongue_winking_eye:
