### ISSUE TITLE
Any plan to support datetime-local?

### ISSUE THREAD

**Issue by frugan-dev** [KreutzerCode/configurable-date-input-polyfill#11]
https://caniuse.com/mdn-html_elements_input_type_datetime-local

**Comment by KreutzerCode** [comment]
Hi @frugan-dev,
there are currently no plans to support datetime-local. 

However, if you have a concept in mind, it would be great if you could submit a pull request and we can work out a feature together.

**Comment by frugan-dev** [comment]
Hi @KreutzerCode,
it seems like a reasonable proposal! :wink:
For now I don't have anything in mind, and the time available isn't much either... but as soon as possible, if no one has come forward before, I'll try to sketch something out!
