### ISSUE TITLE
How to support date elements in containers with z index?

### ISSUE THREAD

**Issue by zilkerfinancial** [KreutzerCode/configurable-date-input-polyfill#8]
I have a data input in a virtual modal window that is in front of the window content by using a z index (in this case 1050). When the picker renders it is underneath the modal window because it does not have a z index and it is attached to the body instead of the input or its container.

Is there a way to give it a z index or attach to the date input?

Thanks!

**Comment by KreutzerCode** [comment]
Hi @zilkerfinancial 
I understand the problem, unfortunately the picker is designed to be placed in the document body.
However, there is a possibility to customize the picker regarding the z-index to your needs. All you need to do is to open the already downloaded datepicker in the IDE of your choice and adjust the scss file it contains to your needs.

To test your changes you have to execute the command `npm run build` in the console to apply the changes.

When you are satisfied with the changes, it is recommended to run the command `npm run production`. This will optimize the code for use in the production environment.

More detailed information can be found in the README.md.

If I can help you further or you have problems with the implementation of your changes, I am happy to help!

**Comment by zilkerfinancial** [comment]
Thanks for your help!

I can definitely change the scss, would you suggest that I add a class to target or add an attribute in the date input and when the code handles the click from that, set the element z index to pull it up?

**Comment by KreutzerCode** [comment]
The easiest way would be to add the needed z-index direct in SCSS to the `date-input-polyfill` element. From my understanding of the situation, no additional CSS class or date picker attribute would be needed to add the required z-index. 

If I have misunderstood something, please explain again why you assume that a css class or an attibute would be necessary.

**Comment by zilkerfinancial** [comment]
I was thinking ahead a bit - in my case I have date fields on the normal page and then in a 'dialog' that uses z index to show up in front. If I put the required z index in an attribute on the input element then the code could be the same for both, and even better, if that change was incorporated then I would not have a custom branch of it. I avoid forked libraries!

Seems like I should just manipulate the item's z index with javascript, i.e. $('data-input-polyfill').css('z-index', xxx);

**Comment by KreutzerCode** [comment]
If this approach is possible for you, I would definitely recommend it! You are absolutely right that fork is to be avoided when it comes to such minimal adjustments. 

Please provide feedback on how your approach worked for you so others can use this information and we can close this issue.

**Comment by zilkerfinancial** [comment]
Thanks again for the help - setting the z index on the containing element worked great, much appreciated!
